sudo: required
services:
    - docker

before_install:
    - docker build -t coanjos/roleta-russa-api-test -f dev.Dockerfile .

script:
    - docker run -e MONGODB_URL=$MONGODB_URL -e JWT_SECRET=$JWT_SECRET coanjos/roleta-russa-api-test npm run test

after_success:
    - docker build -t coanjos/roleta-russa-api .
    # Login
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push to Docker Hub
    - docker push coanjos/roleta-russa-api

deploy:
    edge: true
    provider: elasticbeanstalk
    region: sa-east-1
    app: roleta-russa-api
    env: RoletaRussaApi-env
    bucket_name: elasticbeanstalk-sa-east-1-491740408545
    bucket_path: roleta-russa-api
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY