sudo: required
services:
    - docker

before_install:
    - docker build -t coanjos/roleta-russa-api-test -f dev.Dockerfile .

script:
    - docker run coanjos/roleta-russa-api-test npm test -- --coverage
